spring.application.name=dulcebom

spring.datasource.url=jdbc:mysql://bulkn7bsleewfjjzhl2n-mysql.services.clever-cloud.com:3306/bulkn7bsleewfjjzhl2n
spring.datasource.username=udtkf26ezitgaitt
spring.datasource.password=966915c68f011df0ba859acf0453d15f
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=dulcebom.sistema@gmail.com
spring.mail.password=bfbawwmnspplhykq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

cloudinary.cloud-name=drmhaimrx
cloudinary.api-key=774925683788114
cloudinary.api-secret=UsQtIm8j748giL0jEZ6BtoI6_Fc
app.base-url=http://localhost:8080
